module.exports = {
    printWidth: 100,
    tabWidth: 4,
    useTabs: false,
    semi: true,
    quoteProps: 'as-needed',
    singleQuote: true,
    jsxSingleQuote: true,
    trailingComma: 'es5',
    bracketSpacing: true,
    jsxBracketSameLine: true,
    arrowParens: 'avoid',
    requirePragma: false,
    insertPragma: false,
    endOfLine: 'lf',
    proseWrap: 'always',
};
